version: 1
force:
  major: 1
  minor: 0
  patch: 1
  commit: ef25e22417a3c855a407a5f017e8182f9f7d5cfa
wording:
  patch:
    - update
    - initial
  minor:
    - change
    - improve
  major:
    - breaking
  release:
    - release-candidate
    - add-rc
