apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k9-rapid-alerts
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  groups:
    - name: k9-rapids-alerts
      rules:
      - alert: applikasjon nede
        expr: kube_deployment_status_replicas_available{deployment=~"k9.*|omsorgspenger.*", namespace="omsorgspenger"} == 0
        for: 5m
        annotations:
          consequence: Applikasjon nede
          action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
          summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
        labels:
          namespace: omsorgspenger
          severity: critical

      - alert: kontinuerlig restart
        expr: sum(increase(kube_pod_container_status_restarts_total{container=~"k9.*|omsorgspenger.*", namespace="omsorgspenger"}[30m])) by (container, pod, namespace) > 5
        for: 5m
        annotations:
          consequence: Problem som må undersøkes
          action: "`kubectl describe pod {{ $labels.pod }}` -> `kubectl logs {{ $labels.pod }}`"
          summary: "App {{ $labels.pod }} restarter i namespace {{ $labels.namespace }}"
        labels:
          namespace: omsorgspenger
          severity: warning

      - alert: uloeste behov i rapid
        expr: sum(uloesteBehov{app="k9-vaktmester", paaVent="false"}) > 0
        for: 60m
        annotations:
          consequence: Søknader som sitter fast
          action: "Filtrere på level: error i kibana for å se hva som feiler."
          summary: "Uloeste behov i k9-rapiden har blitt republisert av k9-vaktmester i >60m. Republisering skjer kun i arbeidstid."
        labels:
          namespace: omsorgspenger
          severity: critical
