apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: k9-rapid-v2
  namespace: omsorgspenger
  labels:
    team: omsorgspenger
spec:
  pool: {{pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 6
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 672  # -1 means unlimited
  acl:
    - team: omsorgspenger
      application: k9-vaktmester
      access: readwrite
    - team: omsorgspenger
      application: k9-personopplysninger
      access: readwrite
    - team: omsorgspenger
      application: omsorgspenger-journalforing
      access: readwrite
    - team: omsorgspenger
      application: omsorgspenger-sak
      access: readwrite
    - team: omsorgspenger
      application: omsorgspenger-rammemeldinger
      access: readwrite
    - team: omsorgspenger
      application: omsorgsdager
      access: readwrite
    - team: k9saksbehandling
      application: k9-sak
      access: write
