name: Deploy alerts to NAIS

on:
  push:
    paths-ignore:
      - '**.md'
    paths:
      - 'alerts/*'

jobs:
  deploy-to-dev-and-prod:
    name: Deploy to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [dev-fss, dev-gcp, prod-fss, prod-gcp]
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: alerts/${{ matrix.cluster }}.yml