name: Deploy alerts to NAIS
on:
  push:
    paths:
      - 'alerts/*'
      - '!alerts/README.md'
    branches:
      - master

jobs:
  deploy-to-dev-and-prod:
    name: Deploy to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [dev-fss, dev-gcp, prod-fss, prod-gcp]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: alerts/alerts.yml
