name: Deploy kafka

on:
  push:
    paths:
      - 'kafka/kafkarator.yaml'
      - 'kafka/dev.json'
    branches:
      - master

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka/kafkarator.yaml
          VARS: kafka/dev.json