name: build and publish

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'kafka/*'
      - 'alerts/*'
      - '.github/workflows/deploy-alerts.yml'
      - '.github/workflows/deploy-kafka.yml'
    branches:
      - master

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Set release tag
        run: |
          TAG_NAME="1.$(date "+%Y%m%d%H%M%S")-$(git rev-parse --short HEAD)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - name: Set changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@bc4eb56105a55315b8cf53cfed7e23b9c1c71278
        with:
          fromTag: 2a9ee6b9e0082d9d2559d05c363ecd6f4e4fbc4b

      - name: Publish packages
        run: ./gradlew -Pversion=$RELEASE_TAG build publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: |
            Changes in this release

            ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false
