name: build and publish

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - 'kafka/oneshot.json'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: test and build
        run: ./gradlew -Pversion="1.$(git rev-parse --short HEAD)" build publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set release tag
        run: |
          export TAG_NAME="1.$(git rev-parse --short HEAD)"
          echo "RELEASE_TAG::$TAG_NAME" >> $GITHUB_ENV
      - name: Set changelog
        # (Escape newlines see https://github.com/actions/create-release/issues/25)
        run: |
          text="$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")"
          text="${text//$'%'/%25}"
          text="${text//$'\n'/%0A}"
          text="${text//$'\r'/%0D}"
          echo "CHANGELOG::$text" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: |
            Changes in this Release
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
